name: workflow-1
on:
  workflow_dispatch: {}
jobs:
  workflow-1:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Output
        shell: bash
        run: |
          echo "This is branch ${{ github.ref }}"
