name: workflow-2
on:
  workflow_run:
    workflows: [workflow-1]
    types: [completed]
    #branches: [main, docker-17]
  workflow_dispatch: {}
jobs:
  workflow-2:
    if: ${{ github.event.workflow_dispatch != null || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Debug Output
        shell: bash
        run: |
          echo "Branch is ${{ github.ref }}"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Debug Output After Checkout
        shell: bash
        run: |
          cat branch-indicator

