name: workflow-2
on:
  workflow_run:
    workflows: [workflow-1]
    types: [completed]
    branches: [a, b]
  workflow_dispatch: {}
jobs:
  workflow-2:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Debug Output
        shell: bash
        run: |
          echo "Branch is ${{ github.ref }}"
          echo "Branch of triggering workflow is ${{ github.event.workflow_run.head_branch }}"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.workflow_dispatch.ref || github.event.workflow_run.head_branch }}
      - name: Debug Output After Checkout
        shell: bash
        run: |
          cat branch-indicator

